// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4KUfQoOBhgovlRXaNs7e0hqeFFKAKlM',
    appId: '1:330402609443:web:572d4db4f35b1a2dcdb496',
    messagingSenderId: '330402609443',
    projectId: 'diet-career-buddy',
    authDomain: 'diet-career-buddy.firebaseapp.com',
    storageBucket: 'diet-career-buddy.firebasestorage.app',
    measurementId: 'G-V1STWG25FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB6pYiMMm_ydaQXSWPaQB3at3FvwN_mKg',
    appId: '1:330402609443:android:183f256d188917c1cdb496',
    messagingSenderId: '330402609443',
    projectId: 'diet-career-buddy',
    storageBucket: 'diet-career-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy9QfECtpKG6rBIn-81HYXWimB8EN3ayw',
    appId: '1:330402609443:ios:e349d447e30a0632cdb496',
    messagingSenderId: '330402609443',
    projectId: 'diet-career-buddy',
    storageBucket: 'diet-career-buddy.firebasestorage.app',
    androidClientId: '330402609443-eu6qpp1tfogg7kdd4jgpk8setvinis7k.apps.googleusercontent.com',
    iosClientId: '330402609443-395s7aje66bkp2ol5idbbohmm6qdf4pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietCareerBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy9QfECtpKG6rBIn-81HYXWimB8EN3ayw',
    appId: '1:330402609443:ios:e349d447e30a0632cdb496',
    messagingSenderId: '330402609443',
    projectId: 'diet-career-buddy',
    storageBucket: 'diet-career-buddy.firebasestorage.app',
    androidClientId: '330402609443-eu6qpp1tfogg7kdd4jgpk8setvinis7k.apps.googleusercontent.com',
    iosClientId: '330402609443-395s7aje66bkp2ol5idbbohmm6qdf4pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietCareerBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4KUfQoOBhgovlRXaNs7e0hqeFFKAKlM',
    appId: '1:330402609443:web:0489ae4999ccf74bcdb496',
    messagingSenderId: '330402609443',
    projectId: 'diet-career-buddy',
    authDomain: 'diet-career-buddy.firebaseapp.com',
    storageBucket: 'diet-career-buddy.firebasestorage.app',
    measurementId: 'G-4BV24YWCBV',
  );
}
